[0m12:13:32.682130 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f6be64b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f6c4d6ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f6be65d10>]}


============================== 12:13:32.693593 | ad91c8fd-4b9f-4a0a-a8fe-cefefdeee234 ==============================
[0m12:13:32.693593 [info ] [MainThread]: Running with dbt=1.7.4
[0m12:13:32.700102 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/habte/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:13:32.702580 [error] [MainThread]: Encountered an error:
string indices must be integers, not 'str'
[0m12:13:32.709528 [error] [MainThread]: Traceback (most recent call last):
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/task/init.py", line 317, in run
    profile_name = self.get_profile_name_from_current_project()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/task/init.py", line 142, in get_profile_name_from_current_project
    return dbt_project["profile"]
           ~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

[0m12:13:32.716032 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.041620255, "process_user_time": 6.093162, "process_kernel_time": 0.736624, "process_mem_max_rss": "100896", "process_in_blocks": "123568", "process_out_blocks": "8", "command_success": false}
[0m12:13:32.717938 [debug] [MainThread]: Command `dbt init` failed at 12:13:32.717387 after 0.04 seconds
[0m12:13:32.719571 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f6c4d6810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f6c8ff150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2f6c8ff250>]}
[0m12:13:32.721094 [debug] [MainThread]: Flushing usage events
[0m12:46:24.333089 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b449a73d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b442def90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b442def10>]}


============================== 12:46:24.345351 | 0be14e45-e58d-4e0c-bba9-9ee89fe6b90d ==============================
[0m12:46:24.345351 [info ] [MainThread]: Running with dbt=1.7.4
[0m12:46:24.347756 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/habte/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:46:24.350072 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m12:46:24.369994 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.047233384, "process_user_time": 5.990255, "process_kernel_time": 0.70449, "process_mem_max_rss": "100620", "process_in_blocks": "93312", "process_out_blocks": "16", "command_success": false}
[0m12:46:24.375040 [debug] [MainThread]: Command `dbt run` failed at 12:46:24.374380 after 0.05 seconds
[0m12:46:24.391411 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b448598d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b4887c5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b4887c510>]}
[0m12:46:24.399169 [debug] [MainThread]: Flushing usage events
[0m12:47:58.917699 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7feaae166910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7feaae166990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7feaae166d90>]}


============================== 12:47:58.927444 | a4e75b69-9dd4-4d65-b90f-4fdbd25e5f3f ==============================
[0m12:47:58.927444 [info ] [MainThread]: Running with dbt=1.7.4
[0m12:47:58.929807 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:47:58.932607 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m12:47:58.936081 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.023318393, "process_user_time": 5.864272, "process_kernel_time": 0.396124, "process_mem_max_rss": "100972", "process_in_blocks": "6448", "process_out_blocks": "8", "command_success": false}
[0m12:47:58.938701 [debug] [MainThread]: Command `dbt run` failed at 12:47:58.937895 after 0.03 seconds
[0m12:47:58.940617 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7feaae91f210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7feaae7f2290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7feab2a12b50>]}
[0m12:47:58.943018 [debug] [MainThread]: Flushing usage events
[0m13:01:49.668336 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febbc052750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febbc7c9a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febbc053590>]}


============================== 13:01:49.681309 | 52886da4-35db-40f0-a943-eb05c8cb1f8b ==============================
[0m13:01:49.681309 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:01:49.683749 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir /home/habte/.dbt --profile my_DBT', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:01:49.686078 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m13:01:49.692113 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.028722743, "process_user_time": 5.588907, "process_kernel_time": 0.336029, "process_mem_max_rss": "101096", "process_in_blocks": "624", "process_out_blocks": "16", "command_success": false}
[0m13:01:49.698486 [debug] [MainThread]: Command `dbt run` failed at 13:01:49.693733 after 0.03 seconds
[0m13:01:49.701356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febbc073f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febbe98fc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febbcb15c50>]}
[0m13:01:49.703217 [debug] [MainThread]: Flushing usage events
[0m13:01:52.139922 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m13:23:28.720314 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7a4ad50650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7a4b30ab90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7a4b441a50>]}


============================== 13:23:28.735212 | 20e11743-203d-45ce-938d-e31a58e50179 ==============================
[0m13:23:28.735212 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:23:28.737607 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'debug': 'False', 'fail_fast': 'False', 'log_path': '/home/habte/WEEK02/DBT/logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:23:28.745461 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  The profiles.yml file at /home/habte/WEEK02/DBT/profiles.yml is empty
  
[0m13:23:28.753752 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.041903727, "process_user_time": 5.928982, "process_kernel_time": 0.497424, "process_mem_max_rss": "100792", "process_in_blocks": "52016", "process_out_blocks": "16", "command_success": false}
[0m13:23:28.756196 [debug] [MainThread]: Command `dbt run` failed at 13:23:28.755556 after 0.04 seconds
[0m13:23:28.758099 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7a4ad5a0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7a4f2f2990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7a4f2f0690>]}
[0m13:23:28.760035 [debug] [MainThread]: Flushing usage events
[0m13:25:47.534772 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e621ddc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e62864a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e621de4d0>]}


============================== 13:25:47.543157 | 7f569b0f-a389-44d4-8aaf-78e7268a4497 ==============================
[0m13:25:47.543157 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:25:47.545944 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/home/habte/WEEK02/DBT/logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:25:47.554808 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  The profiles.yml file at /home/habte/WEEK02/DBT/profiles.yml is empty
  
[0m13:25:47.558252 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.030007707, "process_user_time": 5.765364, "process_kernel_time": 0.380089, "process_mem_max_rss": "100836", "process_in_blocks": "544", "process_out_blocks": "8", "command_success": false}
[0m13:25:47.560503 [debug] [MainThread]: Command `dbt run` failed at 13:25:47.559872 after 0.03 seconds
[0m13:25:47.563412 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e62864a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e66a8e9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e62991910>]}
[0m13:25:47.565134 [debug] [MainThread]: Flushing usage events
[0m13:26:32.903972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd09a4619d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd09aa09f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd09ab2b2d0>]}


============================== 13:26:32.912386 | 842429ce-e66f-4b7d-af34-f2a75b55d82a ==============================
[0m13:26:32.912386 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:26:32.915316 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'version_check': 'True', 'warn_error': 'None', 'log_path': '/home/habte/WEEK02/DBT/logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:26:32.924838 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  The profiles.yml file at /home/habte/WEEK02/DBT/profiles.yml is empty
  
[0m13:26:32.928358 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.030813709, "process_user_time": 5.803353, "process_kernel_time": 0.337124, "process_mem_max_rss": "101056", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m13:26:32.930527 [debug] [MainThread]: Command `dbt run` failed at 13:26:32.929857 after 0.03 seconds
[0m13:26:32.935127 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd09b84fe90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd09a457f50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd09a9dd710>]}
[0m13:26:32.937101 [debug] [MainThread]: Flushing usage events
[0m13:34:22.392071 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24f0c81b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24f23b8d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24f1242150>]}


============================== 13:34:22.402578 | 86ecb78d-bb34-4f4b-9409-ddb8490f56cd ==============================
[0m13:34:22.402578 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:34:22.405782 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/home/habte/WEEK02/DBT/logs', 'profiles_dir': '/home/habte/WEEK02/DBT', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:34:22.420662 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  The profiles.yml file at /home/habte/WEEK02/DBT/profiles.yml is empty
  
[0m13:34:22.435168 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_wall_clock_time": 0.048095696, "process_user_time": 5.875248, "process_kernel_time": 0.417986, "process_mem_max_rss": "100832", "process_in_blocks": "24", "process_out_blocks": "8", "command_success": false}
[0m13:34:22.437800 [debug] [MainThread]: Command `dbt docs generate` failed at 13:34:22.437189 after 0.06 seconds
[0m13:34:22.440332 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24f0a9ff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24f0c8add0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24f51eaad0>]}
[0m13:34:22.443495 [debug] [MainThread]: Flushing usage events
[0m13:41:06.492597 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4d7bcced90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4d7c179210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4d7c1953d0>]}


============================== 13:41:06.501178 | 5d0ff4ac-bba3-40c8-a873-592c29981f44 ==============================
[0m13:41:06.501178 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:41:06.504356 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'debug': 'False', 'version_check': 'True', 'log_path': '/home/habte/WEEK02/DBT/logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:41:06.522157 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  The profiles.yml file at /home/habte/WEEK02/DBT/profiles.yml is empty
  
[0m13:41:06.568926 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_wall_clock_time": 0.08262467, "process_user_time": 5.478709, "process_kernel_time": 0.351148, "process_mem_max_rss": "101024", "process_in_blocks": "104", "process_out_blocks": "16", "command_success": false}
[0m13:41:06.654077 [debug] [MainThread]: Command `dbt docs generate` failed at 13:41:06.653415 after 0.17 seconds
[0m13:41:06.669608 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4d7bcd6d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4d7baebd50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4d7bccf290>]}
[0m13:41:06.680205 [debug] [MainThread]: Flushing usage events
[0m13:47:33.177025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43ddfdc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43ddfead0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43dce0ad0>]}


============================== 13:47:33.185083 | ec30b150-3f33-44dd-8a67-80dd9c3fbec7 ==============================
[0m13:47:33.185083 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:47:33.187441 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'version_check': 'True', 'debug': 'False', 'log_path': '/home/habte/WEEK02/DBT/logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:47:34.237823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ec30b150-3f33-44dd-8a67-80dd9c3fbec7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43d3b4290>]}
[0m13:47:35.199664 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'ec30b150-3f33-44dd-8a67-80dd9c3fbec7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43d6c7910>]}
[0m13:47:35.249765 [info ] [MainThread]: Registered adapter: postgres=1.7.4
[0m13:47:35.329648 [debug] [MainThread]: checksum: 248e8aba381ba2d577dce7ab50d2010c2aac45d2b27e6e6214cdd96d2d41fabc, vars: {}, profile: , target: , version: 1.7.4
[0m13:47:35.337231 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m13:47:35.340409 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'ec30b150-3f33-44dd-8a67-80dd9c3fbec7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43dcc5610>]}
[0m13:47:38.219871 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.myproject1
- models.myproject2.example
[0m13:47:38.249446 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ec30b150-3f33-44dd-8a67-80dd9c3fbec7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43d1c3790>]}
[0m13:47:38.259029 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ec30b150-3f33-44dd-8a67-80dd9c3fbec7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43d1fbdd0>]}
[0m13:47:38.263626 [info ] [MainThread]: Found 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[0m13:47:38.271943 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ec30b150-3f33-44dd-8a67-80dd9c3fbec7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43d169590>]}
[0m13:47:38.281764 [info ] [MainThread]: 
[0m13:47:38.284354 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:47:38.288902 [debug] [MainThread]: Command end result
[0m13:47:38.401048 [debug] [MainThread]: Acquiring new postgres connection 'generate_catalog'
[0m13:47:38.402716 [info ] [MainThread]: Building catalog
[0m13:47:38.480706 [info ] [MainThread]: Catalog written to /home/habte/WEEK02/DBT/target/catalog.json
[0m13:47:38.484768 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": true, "command_wall_clock_time": 5.451292, "process_user_time": 9.122427, "process_kernel_time": 0.520244, "process_mem_max_rss": "110868", "process_in_blocks": "34976", "process_out_blocks": "5208"}
[0m13:47:38.493242 [debug] [MainThread]: Command `dbt docs generate` succeeded at 13:47:38.492582 after 5.46 seconds
[0m13:47:38.498971 [debug] [MainThread]: Connection 'generate_catalog' was properly closed.
[0m13:47:38.501201 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43dcc5bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43d6a9dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe43da9f910>]}
[0m13:47:38.503529 [debug] [MainThread]: Flushing usage events
[0m13:47:46.471132 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m13:49:49.616618 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0280e37490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0281496310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0280e34fd0>]}


============================== 13:49:49.628540 | 01834fc7-3953-4b9d-9c0a-244814686e24 ==============================
[0m13:49:49.628540 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:49:49.631848 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'debug': 'False', 'version_check': 'True', 'log_path': '/home/habte/WEEK02/DBT/logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt docs serve', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:49:50.595274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '01834fc7-3953-4b9d-9c0a-244814686e24', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f02815dae50>]}
[0m13:49:50.890236 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '01834fc7-3953-4b9d-9c0a-244814686e24', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f02814b8fd0>]}
[0m13:49:51.721222 [error] [MainThread]: Encountered an error:
[Errno 98] Address already in use
[0m13:49:51.740022 [error] [MainThread]: Traceback (most recent call last):
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 197, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 244, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/main.py", line 324, in docs_serve
    results = task.run()
              ^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/task/serve.py", line 23, in run
    with socketserver.TCPServer(("", port), SimpleHTTPRequestHandler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/home/habte/anaconda3/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

[0m13:49:51.763270 [debug] [MainThread]: Resource report: {"command_name": "serve", "command_wall_clock_time": 2.2821202, "process_user_time": 6.412234, "process_kernel_time": 0.376956, "process_mem_max_rss": "107204", "process_in_blocks": "760", "process_out_blocks": "2960", "command_success": false}
[0m13:49:51.779751 [debug] [MainThread]: Command `dbt docs serve` failed at 13:49:51.773752 after 2.29 seconds
[0m13:49:51.800184 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0280e88d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0281496990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0281496690>]}
[0m13:49:51.819998 [debug] [MainThread]: Flushing usage events
[0m13:50:58.924701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad0ae6f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad0ae4510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad0ae4110>]}


============================== 13:50:58.936695 | acc92b0e-f678-4428-a5a4-8399749eb3d9 ==============================
[0m13:50:58.936695 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:50:58.940336 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'log_path': '/home/habte/WEEK02/DBT/logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m13:51:00.040851 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'acc92b0e-f678-4428-a5a4-8399749eb3d9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad1161ed0>]}
[0m13:51:00.430703 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'acc92b0e-f678-4428-a5a4-8399749eb3d9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad06d35d0>]}
[0m13:51:00.433311 [info ] [MainThread]: Registered adapter: postgres=1.7.4
[0m13:51:00.476998 [debug] [MainThread]: checksum: 248e8aba381ba2d577dce7ab50d2010c2aac45d2b27e6e6214cdd96d2d41fabc, vars: {}, profile: , target: , version: 1.7.4
[0m13:51:00.739360 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m13:51:00.741139 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m13:51:00.743138 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.myproject2.example
- models.myproject1
[0m13:51:00.777562 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'acc92b0e-f678-4428-a5a4-8399749eb3d9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad12758d0>]}
[0m13:51:00.851861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'acc92b0e-f678-4428-a5a4-8399749eb3d9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad05d1050>]}
[0m13:51:00.854098 [info ] [MainThread]: Found 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[0m13:51:00.860235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'acc92b0e-f678-4428-a5a4-8399749eb3d9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad3e29310>]}
[0m13:51:00.866439 [info ] [MainThread]: 
[0m13:51:00.868405 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:51:00.870748 [debug] [MainThread]: Command end result
[0m13:51:00.968396 [info ] [MainThread]: 
[0m13:51:00.980208 [info ] [MainThread]: [32mCompleted successfully[0m
[0m13:51:01.007909 [info ] [MainThread]: 
[0m13:51:01.015180 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[0m13:51:01.026188 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": true, "command_wall_clock_time": 2.2544868, "process_user_time": 6.941815, "process_kernel_time": 0.443349, "process_mem_max_rss": "110780", "process_in_blocks": "144", "process_out_blocks": "1512"}
[0m13:51:01.045912 [debug] [MainThread]: Command `dbt seed` succeeded at 13:51:01.039464 after 2.27 seconds
[0m13:51:01.056078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad1170a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad1171010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2ad118c150>]}
[0m13:51:01.066753 [debug] [MainThread]: Flushing usage events
[0m13:51:34.664802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcff1d910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcff47b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcff67bd0>]}


============================== 13:51:34.673040 | 801b6361-0f3d-496e-ad8f-b3654bc5ee7c ==============================
[0m13:51:34.673040 [info ] [MainThread]: Running with dbt=1.7.4
[0m13:51:34.676299 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/WEEK02/DBT', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/home/habte/WEEK02/DBT/logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt snapshot', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:51:35.476060 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '801b6361-0f3d-496e-ad8f-b3654bc5ee7c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcff6cb90>]}
[0m13:51:35.832185 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '801b6361-0f3d-496e-ad8f-b3654bc5ee7c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bd06c5b50>]}
[0m13:51:35.837200 [info ] [MainThread]: Registered adapter: postgres=1.7.4
[0m13:51:35.869452 [debug] [MainThread]: checksum: 248e8aba381ba2d577dce7ab50d2010c2aac45d2b27e6e6214cdd96d2d41fabc, vars: {}, profile: , target: , version: 1.7.4
[0m13:51:36.105958 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m13:51:36.107847 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m13:51:36.109883 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.myproject1
- models.myproject2.example
[0m13:51:36.150192 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '801b6361-0f3d-496e-ad8f-b3654bc5ee7c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcff6df10>]}
[0m13:51:36.207557 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '801b6361-0f3d-496e-ad8f-b3654bc5ee7c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcfa10e50>]}
[0m13:51:36.209699 [info ] [MainThread]: Found 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[0m13:51:36.212554 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '801b6361-0f3d-496e-ad8f-b3654bc5ee7c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bcfcf6990>]}
[0m13:51:36.221127 [info ] [MainThread]: 
[0m13:51:36.240027 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:51:36.246514 [debug] [MainThread]: Command end result
[0m13:51:36.303757 [debug] [MainThread]: Resource report: {"command_name": "snapshot", "command_success": true, "command_wall_clock_time": 1.7861019, "process_user_time": 6.898457, "process_kernel_time": 0.408145, "process_mem_max_rss": "110820", "process_out_blocks": "1512", "process_in_blocks": "0"}
[0m13:51:36.309045 [debug] [MainThread]: Command `dbt snapshot` succeeded at 13:51:36.308376 after 1.79 seconds
[0m13:51:36.314608 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bd05a3190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bd06df210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7bd05accd0>]}
[0m13:51:36.318224 [debug] [MainThread]: Flushing usage events
